[project]
name = "ee2-music-editor"
version = "0.1.0"
description = "Soundtrack editor for EE2/EE2(AoS) games"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "flet[all]==0.25.2",
    "pydantic==2.10.4",
    "ffmpeg-python==0.2.0",
    "mutagen==1.47.0",
    "pyinstaller==6.11.1",
]

[dependency-groups]
dev = [
    "pre-commit==4.0.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
select = ["E", "F", "I"]
